apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/Mathpro1412/platform-k8s-app-config-prod.git//manifests?ref=main
images:
  - name: anonja/js-web-app
    newTag: 8f6d5ec
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/env: prod
